version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: redis
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: ./djangoprojcelery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangoprojcelery:/usr/src/app
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=duhdenwnei
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./djangoprojcelery 
    command: celery -A djangoprojcelery worker --loglevel=info -Q tasks
    volumes:
      - ./djangoprojcelery:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=duhdenwnei
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - django
      - rabbitmq
  
  # celery2:
  #   container_name: celery2
  #   build:
  #     context: ./celeryworkerstandalone
  #     dockerfile: ./Dockerfile
  #   command: celery -A celerytask worker --loglevel=info -Q queue2
  #   volumes:
  #     - ./celeryworkerstandalone:/usr/src/app/
  #   depends_on:
  #     - redis
  #     - django